// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using b3.Core.Databases;

#nullable disable

namespace BasketAPI.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    [Migration("20231004073052_asdsa")]
    partial class asdsa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("b3.Core.Models.Basket", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CustomerId");

                    b.HasKey("CustomerId");

                    b.ToTable("Baskets", (string)null);
                });

            modelBuilder.Entity("b3.Core.Models.BasketItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("Id");

                    b.Property<string>("CustomerBasketId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CustomerBasketId");

                    b.Property<string>("ProductId")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ProductName");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Quantity");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerBasketId");

                    b.ToTable("BasketItems", (string)null);
                });

            modelBuilder.Entity("b3.Core.Models.BasketItem", b =>
                {
                    b.HasOne("b3.Core.Models.Basket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("CustomerBasketId");

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("b3.Core.Models.Basket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
